# Generated by Django 4.0.5 on 2022-07-01 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='auther_name',
            new_name='auther',
        ),
    ]
